#!/bin/bash
echo "#!/bin/bash
     
    export WINEPREFIX=\$HOME/LoL_wine-$Wine_version/LoL_Prefix  #wineprefix location
    WINEXE=\$HOME/LoL_wine-$Wine_version/bin/wine               #location of wine executable
     
    cd \$WINEPREFIX/drive_c/Riot\ Games/League\ of\ Legends/RADS/system/
    \$WINEXE \"rads_user_kernel.exe\" run lol_launcher \$(ls ../projects/lol_launcher/releases/) LoLLauncher.exe &
     
    loltask_instance=\$(ps -A | grep loltask)
    if [ ! \"\$loltask_instance\" ]; then

           # change kdesu to gksu if u don't use KDE
           kdesu loltask & 

    else
           echo \"loltask is already started. You do not want it to be started again.\"
    fi
     
    " > $HOME/Desktop/Play_LeagueOfLegends.sh
     
    chmod +x $HOME/Desktop/Play_LeagueOfLegends.sh
     
