/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -m -i dbusmenutypes_p.h -p app_menu /media/MyBook/appmenu/src/com.canonical.AppMenu.Registrar.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "app_menu.h"

/*
 * Implementation of interface class ComCanonicalAppMenuRegistrarInterface
 */

ComCanonicalAppMenuRegistrarInterface::ComCanonicalAppMenuRegistrarInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

ComCanonicalAppMenuRegistrarInterface::~ComCanonicalAppMenuRegistrarInterface()
{
}


#include "app_menu.moc"
