/* Generated by the Systemtap dtrace wrapper */

#undef STAP_HAS_SEMAPHORES


#include <sys/sdt.h>

/* GLIB_MEM_ALLOC ( void*, unsigned int, unsigned int, unsigned int) */
#if defined STAP_SDT_V1
#define GLIB_MEM_ALLOC_ENABLED() __builtin_expect (mem__alloc_semaphore, 0)
#define glib_mem__alloc_semaphore mem__alloc_semaphore
#else
#define GLIB_MEM_ALLOC_ENABLED() __builtin_expect (glib_mem__alloc_semaphore, 0)
#endif
__extension__ extern unsigned short glib_mem__alloc_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define GLIB_MEM_ALLOC(arg1,arg2,arg3,arg4) \
STAP_PROBE4(glib,mem__alloc,arg1,arg2,arg3,arg4)

/* GLIB_MEM_REALLOC ( void*, void *, unsigned int, unsigned int) */
#if defined STAP_SDT_V1
#define GLIB_MEM_REALLOC_ENABLED() __builtin_expect (mem__realloc_semaphore, 0)
#define glib_mem__realloc_semaphore mem__realloc_semaphore
#else
#define GLIB_MEM_REALLOC_ENABLED() __builtin_expect (glib_mem__realloc_semaphore, 0)
#endif
__extension__ extern unsigned short glib_mem__realloc_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define GLIB_MEM_REALLOC(arg1,arg2,arg3,arg4) \
STAP_PROBE4(glib,mem__realloc,arg1,arg2,arg3,arg4)

/* GLIB_MEM_FREE ( void*) */
#if defined STAP_SDT_V1
#define GLIB_MEM_FREE_ENABLED() __builtin_expect (mem__free_semaphore, 0)
#define glib_mem__free_semaphore mem__free_semaphore
#else
#define GLIB_MEM_FREE_ENABLED() __builtin_expect (glib_mem__free_semaphore, 0)
#endif
__extension__ extern unsigned short glib_mem__free_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define GLIB_MEM_FREE(arg1) \
STAP_PROBE1(glib,mem__free,arg1)

/* GLIB_SLICE_ALLOC ( void*, unsigned int) */
#if defined STAP_SDT_V1
#define GLIB_SLICE_ALLOC_ENABLED() __builtin_expect (slice__alloc_semaphore, 0)
#define glib_slice__alloc_semaphore slice__alloc_semaphore
#else
#define GLIB_SLICE_ALLOC_ENABLED() __builtin_expect (glib_slice__alloc_semaphore, 0)
#endif
__extension__ extern unsigned short glib_slice__alloc_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define GLIB_SLICE_ALLOC(arg1,arg2) \
STAP_PROBE2(glib,slice__alloc,arg1,arg2)

/* GLIB_SLICE_FREE ( void*, unsigned int) */
#if defined STAP_SDT_V1
#define GLIB_SLICE_FREE_ENABLED() __builtin_expect (slice__free_semaphore, 0)
#define glib_slice__free_semaphore slice__free_semaphore
#else
#define GLIB_SLICE_FREE_ENABLED() __builtin_expect (glib_slice__free_semaphore, 0)
#endif
__extension__ extern unsigned short glib_slice__free_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define GLIB_SLICE_FREE(arg1,arg2) \
STAP_PROBE2(glib,slice__free,arg1,arg2)

/* GLIB_QUARK_NEW ( char *, unsigned int) */
#if defined STAP_SDT_V1
#define GLIB_QUARK_NEW_ENABLED() __builtin_expect (quark__new_semaphore, 0)
#define glib_quark__new_semaphore quark__new_semaphore
#else
#define GLIB_QUARK_NEW_ENABLED() __builtin_expect (glib_quark__new_semaphore, 0)
#endif
__extension__ extern unsigned short glib_quark__new_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define GLIB_QUARK_NEW(arg1,arg2) \
STAP_PROBE2(glib,quark__new,arg1,arg2)

