/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -m -i dbusmenutypes_p.h -p dbus_menu /home/kyan/git/appmenu/src/com.canonical.dbusmenu.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "dbus_menu.h"

/*
 * Implementation of interface class ComCanonicalDbusmenuInterface
 */

ComCanonicalDbusmenuInterface::ComCanonicalDbusmenuInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

ComCanonicalDbusmenuInterface::~ComCanonicalDbusmenuInterface()
{
}


#include "dbus_menu.moc"
