#!/bin/sh
#scanner-setup : Wreathe File Scanner Setup Script version 4.0 (4 April 2011)! This script is released under the Affero GPL. http://futuramerlin.com/
rm -rf ~/.Wreathe-File-Scanner
mkdir ~/.Wreathe-File-Scanner
cd ~/.Wreathe-File-Scanner
touch input.scdat
touch output.scdat
touch log.scdat
