#!/bin/sh
#scanner-update : Wreathe File Scanner Update Script version 4.0 (4 April 2011)! This script is released under the Affero GPL. http://futuramerlin.com/
mkdir /tmp/wfscannerupdate
cd /tmp/wfscannerupdate
wget http://futuramerlin.com/scanner-install
cp -f scanner-install ~/scanner-install
cd
./scanner-install
rm -rf /tmp/wfscannerupdate
rm -f ~/scanner-install
