#!/bin/sh
#scanner-uninstall : Wreathe File Scanner Uninstallation Script version 4.0 (4 April 2011)! This script is released under the Affero GPL. http://futuramerlin.com/
rm /usr/bin/scanner.pl
rm /usr/bin/scanner-setup
rm /usr/bin/scanner-update
rm /usr/bin/wfscan
rm /usr/bin/wfscan-help
rm /usr/share/doc/wfscan-help.txt
rm /usr/bin/wfscan-recoll
rm /usr/bin/scanner-uninstall
