/* Generated by the Systemtap dtrace wrapper */

#undef STAP_HAS_SEMAPHORES


#include <sys/sdt.h>

/* GOBJECT_TYPE_NEW ( char *, unsigned long, unsigned long) */
#if defined STAP_SDT_V1
#define GOBJECT_TYPE_NEW_ENABLED() __builtin_expect (type__new_semaphore, 0)
#define gobject_type__new_semaphore type__new_semaphore
#else
#define GOBJECT_TYPE_NEW_ENABLED() __builtin_expect (gobject_type__new_semaphore, 0)
#endif
__extension__ extern unsigned short gobject_type__new_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define GOBJECT_TYPE_NEW(arg1,arg2,arg3) \
STAP_PROBE3(gobject,type__new,arg1,arg2,arg3)

/* GOBJECT_OBJECT_NEW ( void*, unsigned long) */
#if defined STAP_SDT_V1
#define GOBJECT_OBJECT_NEW_ENABLED() __builtin_expect (object__new_semaphore, 0)
#define gobject_object__new_semaphore object__new_semaphore
#else
#define GOBJECT_OBJECT_NEW_ENABLED() __builtin_expect (gobject_object__new_semaphore, 0)
#endif
__extension__ extern unsigned short gobject_object__new_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define GOBJECT_OBJECT_NEW(arg1,arg2) \
STAP_PROBE2(gobject,object__new,arg1,arg2)

/* GOBJECT_OBJECT_REF ( void*, unsigned long, unsigned int) */
#if defined STAP_SDT_V1
#define GOBJECT_OBJECT_REF_ENABLED() __builtin_expect (object__ref_semaphore, 0)
#define gobject_object__ref_semaphore object__ref_semaphore
#else
#define GOBJECT_OBJECT_REF_ENABLED() __builtin_expect (gobject_object__ref_semaphore, 0)
#endif
__extension__ extern unsigned short gobject_object__ref_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define GOBJECT_OBJECT_REF(arg1,arg2,arg3) \
STAP_PROBE3(gobject,object__ref,arg1,arg2,arg3)

/* GOBJECT_OBJECT_UNREF ( void*, unsigned long, unsigned int) */
#if defined STAP_SDT_V1
#define GOBJECT_OBJECT_UNREF_ENABLED() __builtin_expect (object__unref_semaphore, 0)
#define gobject_object__unref_semaphore object__unref_semaphore
#else
#define GOBJECT_OBJECT_UNREF_ENABLED() __builtin_expect (gobject_object__unref_semaphore, 0)
#endif
__extension__ extern unsigned short gobject_object__unref_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define GOBJECT_OBJECT_UNREF(arg1,arg2,arg3) \
STAP_PROBE3(gobject,object__unref,arg1,arg2,arg3)

/* GOBJECT_OBJECT_DISPOSE ( void*, unsigned long, unsigned int) */
#if defined STAP_SDT_V1
#define GOBJECT_OBJECT_DISPOSE_ENABLED() __builtin_expect (object__dispose_semaphore, 0)
#define gobject_object__dispose_semaphore object__dispose_semaphore
#else
#define GOBJECT_OBJECT_DISPOSE_ENABLED() __builtin_expect (gobject_object__dispose_semaphore, 0)
#endif
__extension__ extern unsigned short gobject_object__dispose_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define GOBJECT_OBJECT_DISPOSE(arg1,arg2,arg3) \
STAP_PROBE3(gobject,object__dispose,arg1,arg2,arg3)

/* GOBJECT_OBJECT_DISPOSE_END ( void*, unsigned long, unsigned int) */
#if defined STAP_SDT_V1
#define GOBJECT_OBJECT_DISPOSE_END_ENABLED() __builtin_expect (object__dispose__end_semaphore, 0)
#define gobject_object__dispose__end_semaphore object__dispose__end_semaphore
#else
#define GOBJECT_OBJECT_DISPOSE_END_ENABLED() __builtin_expect (gobject_object__dispose__end_semaphore, 0)
#endif
__extension__ extern unsigned short gobject_object__dispose__end_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define GOBJECT_OBJECT_DISPOSE_END(arg1,arg2,arg3) \
STAP_PROBE3(gobject,object__dispose__end,arg1,arg2,arg3)

/* GOBJECT_OBJECT_FINALIZE ( void*, unsigned long) */
#if defined STAP_SDT_V1
#define GOBJECT_OBJECT_FINALIZE_ENABLED() __builtin_expect (object__finalize_semaphore, 0)
#define gobject_object__finalize_semaphore object__finalize_semaphore
#else
#define GOBJECT_OBJECT_FINALIZE_ENABLED() __builtin_expect (gobject_object__finalize_semaphore, 0)
#endif
__extension__ extern unsigned short gobject_object__finalize_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define GOBJECT_OBJECT_FINALIZE(arg1,arg2) \
STAP_PROBE2(gobject,object__finalize,arg1,arg2)

/* GOBJECT_OBJECT_FINALIZE_END ( void*, unsigned long) */
#if defined STAP_SDT_V1
#define GOBJECT_OBJECT_FINALIZE_END_ENABLED() __builtin_expect (object__finalize__end_semaphore, 0)
#define gobject_object__finalize__end_semaphore object__finalize__end_semaphore
#else
#define GOBJECT_OBJECT_FINALIZE_END_ENABLED() __builtin_expect (gobject_object__finalize__end_semaphore, 0)
#endif
__extension__ extern unsigned short gobject_object__finalize__end_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define GOBJECT_OBJECT_FINALIZE_END(arg1,arg2) \
STAP_PROBE2(gobject,object__finalize__end,arg1,arg2)

/* GOBJECT_SIGNAL_NEW ( unsigned int, char *, unsigned long) */
#if defined STAP_SDT_V1
#define GOBJECT_SIGNAL_NEW_ENABLED() __builtin_expect (signal__new_semaphore, 0)
#define gobject_signal__new_semaphore signal__new_semaphore
#else
#define GOBJECT_SIGNAL_NEW_ENABLED() __builtin_expect (gobject_signal__new_semaphore, 0)
#endif
__extension__ extern unsigned short gobject_signal__new_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define GOBJECT_SIGNAL_NEW(arg1,arg2,arg3) \
STAP_PROBE3(gobject,signal__new,arg1,arg2,arg3)

/* GOBJECT_SIGNAL_EMIT ( unsigned int, unsigned int, void *, unsigned long) */
#if defined STAP_SDT_V1
#define GOBJECT_SIGNAL_EMIT_ENABLED() __builtin_expect (signal__emit_semaphore, 0)
#define gobject_signal__emit_semaphore signal__emit_semaphore
#else
#define GOBJECT_SIGNAL_EMIT_ENABLED() __builtin_expect (gobject_signal__emit_semaphore, 0)
#endif
__extension__ extern unsigned short gobject_signal__emit_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define GOBJECT_SIGNAL_EMIT(arg1,arg2,arg3,arg4) \
STAP_PROBE4(gobject,signal__emit,arg1,arg2,arg3,arg4)

/* GOBJECT_SIGNAL_EMIT_END ( unsigned int, unsigned int, void *, unsigned long) */
#if defined STAP_SDT_V1
#define GOBJECT_SIGNAL_EMIT_END_ENABLED() __builtin_expect (signal__emit__end_semaphore, 0)
#define gobject_signal__emit__end_semaphore signal__emit__end_semaphore
#else
#define GOBJECT_SIGNAL_EMIT_END_ENABLED() __builtin_expect (gobject_signal__emit__end_semaphore, 0)
#endif
__extension__ extern unsigned short gobject_signal__emit__end_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define GOBJECT_SIGNAL_EMIT_END(arg1,arg2,arg3,arg4) \
STAP_PROBE4(gobject,signal__emit__end,arg1,arg2,arg3,arg4)

